services:
  postgres:
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
  node:
    build: ../server
    ports:
      - "5000:5000"
    volumes:
      - ../server:/app
      - /app/node_modules
    depends_on:
      - postgres